PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX dc:   <http://purl.org/dc/elements/1.1/>
PREFIX atih: <http://data.esante.gouv.fr/atih-cim10#>

SELECT ?concept ?code ?label ?type
       ?synonyme ?inclusion_note ?exclusion_note
       ?definition ?scope_note ?structured_exclusion
WHERE {
    ?concept skos:notation ?code .
    ?concept rdfs:label    ?label .
    ?concept dc:type       ?type .
    OPTIONAL { ?concept skos:altLabel      ?synonyme . }
    OPTIONAL { ?concept xkos:inclusionNote ?inclusion_note . }
    OPTIONAL { ?concept xkos:exclusionNote ?exclusion_note . }
    OPTIONAL { ?concept skos:definition    ?definition . }
    OPTIONAL { ?concept skos:scopeNote     ?scope_note . }
    OPTIONAL { ?concept atih:exclusion     ?structured_exclusion . }
}
